In [ ]:
from graph_encode import base_graph_edges,move_to_index,index_to_move,adjacency_list, node_feature_matrix,edge_feature_matrix 

In [ ]:
import numpy as np
import torch

Wu = torch.randn(21, 11)
We = torch.randn(11, 11)
Wv = torch.randn(21, 11)
Wq = torch.randn(21, 3)
W0 = torch.randn(21, 21)
Wh = torch.randn(21, 21)
Wg = torch.randn(11, 21)
a = torch.randn(11)

node_feature_matrix = torch.tensor(node_feature_matrix)
edge_feature_matrix = torch.tensor(edge_feature_matrix)


In [7]:
node_feature_matrix.shape

torch.Size([64, 21])

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
leaky_relu = nn.LeakyReLU(negative_slope=0.01)

In [ ]:
for i, neighborhood in enumerate(adjacency_list):
    gilist = []
    value_list = []
    for j, (node_index, edge_index) in enumerate(neighborhood):
        gijnew = (
            node_feature_matrix[i] @ Wu +
            edge_feature_matrix[edge_index] @ We +
            node_feature_matrix[node_index] @ Wv
        )
        # print(a @ gijnew)       
        # print(leaky_relu(a @ gijnew))
        gilist.append(leaky_relu(a @ gijnew))
        value_list.append(node_feature_matrix[node_index] @ Wh + edge_feature_matrix[edge_index] @ Wg)
    gilist = torch.tensor(gilist)
    value_list =
    hew_i = node_feature_matrix[i] @ W0 + F.softmax(gilist) @ 

torch.Size([28])
torch.Size([34])
torch.Size([35])
torch.Size([35])
torch.Size([35])
torch.Size([35])
torch.Size([34])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([37])
torch.Size([37])
torch.Size([37])
torch.Size([37])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([39])
torch.Size([39])
torch.Size([39])
torch.Size([39])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([39])
torch.Size([41])
torch.Size([41])
torch.Size([39])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([39])
torch.Size([41])
torch.Size([41])
torch.Size([39])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([39])
torch.Size([39])
torch.Size([39])
torch.Size([39])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([35])
torch.Size([37])
torch.Size([37])
torch.Size([37])
torch.Size([37])
torch.Size([35])
torch.Size([28])
torch.Size([28])
torch.Size([34])
torch.Size([35

C:\Users\tan04\AppData\Local\Temp\ipykernel_7312\706452266.py:13: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(F.softmax(gilist).shape)


In [20]:
print(gilist)

tensor([ 2.4274e+01,  1.5476e+01, -2.0496e-02,  1.7685e+01,  1.0581e+01,
        -5.8695e-02,  1.6362e+01,  1.2027e+01, -4.4226e-02,  1.1869e+01,
         1.0303e+01, -6.1469e-02,  1.7284e+01,  8.5790e+00, -7.8711e-02,
         2.8819e+00,  6.3184e+00, -9.5953e-02,  1.4232e+01,  7.1913e+00,
         4.4220e+00,  8.4115e+00,  5.3177e-01, -3.0076e-02, -4.0128e-02,
        -5.4279e-02, -1.1315e-01, -1.0385e-01])


In [ ]:
h_transformed = node_feature_matrix @ Wu  # shape [N, H]
h_v = node_feature_matrix @ Wv            # shape [N, H]
e_transformed = edge_feature_matrix @ We  # shape [E, H]



for i, neighborhood in enumerate(adjacency_list):
    for j, e in neighborhood:
        



Attention shape: torch.Size([64, 41])


In [21]:
print(attention[-2] > 0)
print(sum(attention[-2] > 0))
print(attention[-1])

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False, False, False, False, False, False,
        False])
tensor(34)
tensor([9.9714e-01, 1.5058e-04, 2.8039e-11, 1.3712e-03, 1.1266e-06, 2.6988e-11,
        3.6542e-04, 4.7878e-06, 2.7381e-11, 4.0858e-06, 8.5372e-07, 2.6913e-11,
        9.1873e-04, 1.5223e-07, 2.6453e-11, 5.1081e-10, 1.5875e-08, 2.6001e-11,
        4.3413e-05, 3.8002e-08, 2.3830e-09, 1.2874e-07, 4.8709e-11, 2.7772e-11,
        2.7494e-11, 2.7108e-11, 2.5558e-11, 2.5797e-11, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])


In [17]:
node_feature_matrix @ Wq

array([[-3.61198604, -1.93738445, -6.25167256],
       [-4.07040313, -1.1615429 , -8.17957623],
       [-3.93687297, -1.3179738 , -5.6887551 ],
       [-4.71151851, -1.85908188, -5.9711774 ],
       [-3.58888187, -0.80970125, -6.12105319],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.61198604, -1.93738445, -6.25167256],
       [-2.64527836, -2.03796463, -5.35594498],
       [-2.64527836, -2.03796463, -5.35594498],
       [-2.64527836, -2.03796463, -5.35594498],
       [-2.64527836, -2.03796463, -5.35594498],
       [-3.78361643, -0.90080361, -5.83123073],
       [-2.64527836, -2.03796463, -5.35594498],
       [-2.64527836, -2.03796463, -5.35594498],
       [-2.64527836, -2.03796463, -5.35594498],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.78361643, -0.90080361, -5.83123073],
       [-3.78361643, -0.90080361, -5.831